### ISSUE TITLE
Can't load the graph

### ISSUE THREAD

**Issue by LoneDev6** [FoskyM/flarum-activity-graph#1]
![image](https://github.com/user-attachments/assets/e1617700-668d-49dd-be12-104da1e8eb72)

![image](https://github.com/user-attachments/assets/28a94af6-ef28-4592-95b9-3ce583fa6d12)

**Comment by FoskyM** [comment]
Need debug info to find the problem.

**Comment by LoneDev6** [comment]
```
Flarum core: 1.7.2
PHP version: 8.0.19
MySQL version: 10.5.18-MariaDB-1:10.5.18+maria~ubu2004
Loaded extensions: Core, date, libxml, pcre, zlib, filter, hash, json, readline, Reflection, SPL, session, ctype, curl, dom, fileinfo, gd, gmp, iconv, intl, mbstring, openssl, PDO, standard, tokenizer, xmlwriter, zip, exif, mysqlnd, Phar, pdo_mysql, apcu, Zend OPcache
+------------------------------------+------------+--------+
| Flarum Extensions                  |            |        |
+------------------------------------+------------+--------+
| ID                                 | Version    | Commit |
+------------------------------------+------------+--------+
| flarum-flags                       | v1.7.0     |        |
| flarum-approval                    | v1.7.0     |        |
| flarum-tags                        | v1.7.1     |        |
| flarum-suspend                     | v1.7.0     |        |
| flarum-subscriptions               | v1.7.0     |        |
| askvortsov-auto-moderator          | v0.1.2     |        |
| flarum-likes                       | v1.7.0     |        |
| flarum-sticky                      | v1.7.0     |        |
| flarum-lock                        | v1.7.0     |        |
| afrux-forum-widgets-core           | v0.1.7     |        |
| fof-byobu                          | 1.2.0      |        |
| fof-follow-tags                    | 1.1.7      |        |
| antoinefr-money                    | v1.3.1     |        |
| flarum-markdown                    | v1.7.0     |        |
| zerosonesfun-bbcode-iframe         | 1.0        |        |
| tohsakarat-tags-filter             | v1.0.3     |        |
| the-turk-stickiest                 | 3.0.1      |        |
| the-turk-flamoji                   | 1.0.4      |        |
| the-turk-diff                      | 1.1.2      |        |
| swaggymacro-only-starter           | 0.6.6      |        |
| serakoi-flarumstaffbadge           | 1.2.1      |        |
| ramesh-dada-bbcode-alerts          | 6.21       |        |
| nearata-tags-color-generator       | v2.2.0     |        |
| nearata-lang-italian               | v1.1.0     |        |
| nearata-internal-links-noreload    | v2.1.3     |        |
| nearata-embed-video                | v3.2.1     |        |
| nearata-copy-code-to-clipboard     | v2.1.0     |        |
| michaelbelgium-discussion-views    | v7.2.1     |        |
| lonedev-customer-verify            | dev-main   |        |
| kilowhat-audit-free                | 1.6.0      |        |
| justoverclock-last-users-posts     | 0.3.0      |        |
| ianm-log-viewer                    | 0.1.1      |        |
| fof-webhooks                       | 1.1.2      |        |
| fof-upload                         | 1.2.3      |        |
| fof-terms                          | 1.2.1      |        |
| fof-spamblock                      | 1.1.0      |        |
| fof-reactions                      | 1.1.5      |        |
| fof-pages                          | 1.0.5      |        |
| fof-oauth                          | 1.3.0      |        |
| fof-moderator-notes                | 1.2.0      |        |
| fof-links                          | 1.1.4      |        |
| fof-ignore-users                   | 1.2.0      |        |
| fof-github-autolink                | 1.0.0      |        |
| fof-gamification                   | 1.6.2      |        |
| fof-forum-statistics-widget        | 1.1.0      |        |
| fof-formatting                     | 1.0.3      |        |
| fof-drafts                         | 1.2.2      |        |
| fof-cookie-consent                 | 1.1.1      |        |
| fof-best-answer                    | dev-main   |        |
| fof-analytics                      | 1.1.0      |        |
| flarumite-simple-spoilers          | 1.0.0      |        |
| flarum-statistics                  | v1.7.0     |        |
| flarum-pusher                      | v1.7.0     |        |
| flarum-mentions                    | v1.7.0     |        |
| flarum-lang-turkish                | 1.16.0     |        |
| flarum-lang-spanish                | 1.6.0      |        |
| flarum-lang-french                 | v4.11.0    |        |
| flarum-lang-english                | v1.7.0     |        |
| flarum-lang-chinese-simplified     | v1.3.0     |        |
| flarum-emoji                       | v1.7.0     |        |
| flarum-bbcode                      | v1.7.0     |        |
| davwheat-custom-sidenav-links      | 1.0.1      |        |
| datitisev-discussion-agree-message | 1.0.2      |        |
| club-1-server-side-highlight       | v1.4.0     |        |
| clarkwinkelmann-post-bookmarks     | 1.0.0      |        |
| clarkwinkelmann-money-rewards      | 1.0.0      |        |
| clarkwinkelmann-mass-actions       | 1.1.2      |        |
| clarkwinkelmann-likes-received     | 1.0.2      |        |
| clarkwinkelmann-collapsible-posts  | 1.0.0      |        |
| blomstra-turnstile                 | 0.1.2      |        |
| blomstra-mark-unread               | 0.2.0      |        |
| blomstra-fontawesome               | 0.1.5      |        |
| blomstra-database-queue            | 0.1-beta.2 |        |
| askvortsov-rich-text               | v2.1.7     |        |
| askvortsov-help-tags               | v1.1.0     |        |
+------------------------------------+------------+--------+
Base URL: https://forum.devs.beer
Installation path: /flarum/app
Queue driver: database
Session driver: file
Scheduler status: Never run
Mail driver: smtp
Debug mode: off

```

**Comment by FoskyM** [comment]
Perhaps the problem caused by that core version is lower than **1.8**? I'm not sure because I've only tried it on **1.8**.

But you can turn on the debug mode and paste the **API** output here, so that I can locate the error.

**Comment by LoneDev6** [comment]
```
[2024-09-03 11:02:00] flarum.ERROR: Error: Class "FoF\UserRequest\UsernameRequest" not found in /flarum/app/vendor/foskym/flarum-activity-graph/src/Controllers/ApiActivityGraphController.php:65
Stack trace:
#0 [internal function]: FoskyM\ActivityGraph\Controllers\ApiActivityGraphController->__construct()
#1 /flarum/app/vendor/illuminate/container/Container.php(917): ReflectionClass->newInstanceArgs()
#2 /flarum/app/vendor/illuminate/container/Container.php(758): Illuminate\Container\Container->build()
#3 /flarum/app/vendor/illuminate/container/Container.php(694): Illuminate\Container\Container->resolve()
#4 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(77): Illuminate\Container\Container->make()
#5 /flarum/app/vendor/flarum/core/src/Http/RouteHandlerFactory.php(37): Flarum\Http\RouteHandlerFactory->resolveController()
#6 /flarum/app/vendor/flarum/core/src/Http/Middleware/ExecuteRoute.php(27): Flarum\Http\RouteHandlerFactory->Flarum\Http\{closure}()
#7 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ExecuteRoute->process()
#8 /flarum/app/vendor/kilowhat/flarum-ext-audit-free/src/Middlewares/SetLoggerActor.php(28): Laminas\Stratigility\Next->handle()
#9 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Kilowhat\Audit\Middlewares\SetLoggerActor->process()
#10 /flarum/app/vendor/flarum/core/src/Api/Middleware/ThrottleApi.php(33): Laminas\Stratigility\Next->handle()
#11 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\ThrottleApi->process()
#12 /flarum/app/vendor/flarum/core/src/Http/Middleware/CheckCsrfToken.php(36): Laminas\Stratigility\Next->handle()
#13 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\CheckCsrfToken->process()
#14 /flarum/app/vendor/flarum/core/src/Http/Middleware/ResolveRoute.php(69): Laminas\Stratigility\Next->handle()
#15 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ResolveRoute->process()
#16 /flarum/app/vendor/flarum/core/src/Http/Middleware/SetLocale.php(51): Laminas\Stratigility\Next->handle()
#17 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\SetLocale->process()
#18 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithHeader.php(58): Laminas\Stratigility\Next->handle()
#19 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithHeader->process()
#20 /flarum/app/vendor/flarum/core/src/Http/Middleware/AuthenticateWithSession.php(31): Laminas\Stratigility\Next->handle()
#21 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\AuthenticateWithSession->process()
#22 /flarum/app/vendor/flarum/core/src/Http/Middleware/RememberFromCookie.php(52): Laminas\Stratigility\Next->handle()
#23 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\RememberFromCookie->process()
#24 /flarum/app/vendor/flarum/core/src/Http/Middleware/StartSession.php(61): Laminas\Stratigility\Next->handle()
#25 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\StartSession->process()
#26 /flarum/app/vendor/flarum/core/src/Api/Middleware/FakeHttpMethods.php(29): Laminas\Stratigility\Next->handle()
#27 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Api\Middleware\FakeHttpMethods->process()
#28 /flarum/app/vendor/flarum/core/src/Http/Middleware/ParseJsonBody.php(28): Laminas\Stratigility\Next->handle()
#29 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ParseJsonBody->process()
#30 /flarum/app/vendor/flarum/core/src/Http/Middleware/HandleErrors.php(57): Laminas\Stratigility\Next->handle()
#31 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\HandleErrors->process()
#32 /flarum/app/vendor/flarum/core/src/Http/Middleware/InjectActorReference.php(25): Laminas\Stratigility\Next->handle()
#33 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\InjectActorReference->process()
#34 /flarum/app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#35 /flarum/app/vendor/middlewares/request-handler/src/RequestHandler.php(84): Laminas\Stratigility\MiddlewarePipe->process()
#36 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\RequestHandler->process()
#37 /flarum/app/vendor/middlewares/base-path-router/src/BasePathRouter.php(101): Laminas\Stratigility\Next->handle()
#38 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePathRouter->process()
#39 /flarum/app/vendor/laminas/laminas-stratigility/src/Middleware/OriginalMessages.php(36): Laminas\Stratigility\Next->handle()
#40 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Laminas\Stratigility\Middleware\OriginalMessages->process()
#41 /flarum/app/vendor/middlewares/base-path/src/BasePath.php(73): Laminas\Stratigility\Next->handle()
#42 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Middlewares\BasePath->process()
#43 /flarum/app/vendor/flarum/core/src/Http/Middleware/ProcessIp.php(24): Laminas\Stratigility\Next->handle()
#44 /flarum/app/vendor/laminas/laminas-stratigility/src/Next.php(49): Flarum\Http\Middleware\ProcessIp->process()
#45 /flarum/app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(75): Laminas\Stratigility\Next->handle()
#46 /flarum/app/vendor/laminas/laminas-stratigility/src/MiddlewarePipe.php(64): Laminas\Stratigility\MiddlewarePipe->process()
#47 /flarum/app/vendor/laminas/laminas-httphandlerrunner/src/RequestHandlerRunner.php(73): Laminas\Stratigility\MiddlewarePipe->handle()
#48 /flarum/app/vendor/flarum/core/src/Http/Server.php(45): Laminas\HttpHandlerRunner\RequestHandlerRunner->run()
#49 /flarum/app/public/index.php(26): Flarum\Http\Server->listen()
#50 {main}  
```

**Comment by LoneDev6** [comment]
Seems it's caused by the fact that I don't have [FoF UserRequest](https://flarum.org/extension/fof/username-request) installed.
I don't want to install it, is it possible to fix the issue without installing that extension?

**Comment by FoskyM** [comment]
Sorry I made mistake by loading the class before check. I'll fix it soon.

**Comment by LoneDev6** [comment]
Thanks <3
